export const specialNeeds = {
    "Autism Spectrum Disorder (ASD)": "Autism spectrum disorder (ASD) is a developmental disorder that affects communication and behavior. Although autism can be diagnosed at any age, it is said to be a “developmental disorder” because symptoms generally appear in the first two years of life.​",
    "Attention Deficit Hyperactivity Disorder (ADHD)": "Attention deficit hyperactivity disorder (ADHD) is a neurodevelopmental disorder characterized by inattention, or excessive activity and impulsivity, which are otherwise not appropriate for a person's age. Some individuals with ADHD also display difficulty regulating emotions or problems with executive function.​",
    "Dyslexia": "Dyslexia is a learning disorder that involves difficulty reading due to problems identifying speech sounds and learning how they relate to letters and words (decoding). Also called reading disability, dyslexia affects areas of the brain that process language.​",
    "Dyscalculia": "Dyscalculia is a learning disorder that makes it hard to do math and tasks that involve math. It's not as well known or as understood as dyslexia. But some experts believe it's just as common. That means an estimated 5 to 10 percent of people might have dyscalculia.​",
    "Dysgraphia": "Dysgraphia is a learning disability that affects writing abilities. It can manifest itself as difficulties with spelling, poor handwriting and trouble putting thoughts on paper. Because writing requires a complex set of motor and information processing skills, saying a student has dysgraphia is not sufficient. A student with disorders in written expression will benefit from specific accommodations in the learning environment, as well as additional practice learning the skills required to be an accomplished writer.​",
    "Dyspraxia": "Dyspraxia, also known as developmental co-ordination disorder (DCD), is a common disorder that affects movement and co-ordination. Dyspraxia does not affect your intelligence. It can affect your co-ordination skills and the way you carry out everyday tasks.​",
    "Auditory Processing Disorder (APD)": "Auditory processing disorder (APD), also known as central auditory processing disorder (CAPD), is a hearing problem that affects about 5% of school-aged children. Kids with this condition can't process what they hear in the same way other kids do because their ears and brain don't fully coordinate.​",
    "Visual Processing Disorder (VPD)": "Visual processing disorder (VPD) refers to a reduced ability to make sense of information taken in through the eyes. This is different from problems involving sight or sharpness of vision. Difficulties with visual processing affect how visual information is interpreted, or processed by the brain.​",
    "Nonverbal Learning Disabilities (NVLD)": "Nonverbal learning disabilities (NVLD) are a group of conditions that involve a wide range of academic and social challenges. People with NVLD have difficulties recognizing and interpreting nonverbal cues such as facial expressions, body language, gestures, and tone of voice.​",
}